### ISSUE TITLE
Request- Add your github URL to the script somewhere

### ISSUE THREAD

**Issue by Tharic99** [engels74/mover-status#3]
Could you add your github URL to the script somewhere? This way when I drop it in my User Scripts and look at it again in seven months, I'll see where it came from and know where to check for updates!

Thanks!

**Comment by engels74** [comment]
I can certainly add that.

I've made the script so it'll say [in the footer](https://github.com/engels74/mover-status/blob/f349b835ca6ceb62a3941fc4780e58c458349915/moverStatus.sh#L252-L255) as well, "update available", when there's an update available. But it's a good idea to include as well in the script itself. I'll probably put it in the bottom of the script, together with the copyright notice.

**Comment by engels74** [comment]
The footer update thing doesn't seem to work sadly, guess I'll have to fix that 😅
